version: '3.8'

services:
  # Node.js 18 Test Environment
  test-node18:
    build:
      context: .
      dockerfile: Dockerfile.node18.test
    container_name: ruv-swarm-test-node18
    environment:
      - NODE_VERSION=18
      - TEST_ENV=docker
      - RUST_LOG=warn
      - NODE_OPTIONS=--experimental-wasm-modules
    volumes:
      - ./test-results/node18:/app/test-results
      - ./coverage/node18:/app/coverage
    command: npm run test:docker:comprehensive

  # Node.js 20 Test Environment
  test-node20:
    build:
      context: .
      dockerfile: Dockerfile.node20.test
    container_name: ruv-swarm-test-node20
    environment:
      - NODE_VERSION=20
      - TEST_ENV=docker
      - RUST_LOG=warn
      - NODE_OPTIONS=--experimental-wasm-modules
    volumes:
      - ./test-results/node20:/app/test-results
      - ./coverage/node20:/app/coverage
    command: npm run test:docker:comprehensive

  # Node.js 22 Test Environment
  test-node22:
    build:
      context: .
      dockerfile: Dockerfile.node22.test
    container_name: ruv-swarm-test-node22
    environment:
      - NODE_VERSION=22
      - TEST_ENV=docker
      - RUST_LOG=warn
      - NODE_OPTIONS=--experimental-wasm-modules
    volumes:
      - ./test-results/node22:/app/test-results
      - ./coverage/node22:/app/coverage
    command: npm run test:docker:comprehensive

  # NPX Integration Test
  test-npx:
    build:
      context: .
      dockerfile: Dockerfile.npx.test
    container_name: ruv-swarm-test-npx
    environment:
      - TEST_ENV=docker-npx
      - RUST_LOG=warn
    volumes:
      - ./test-results/npx:/app/test-results
    command: /app/scripts/test-npx-commands.sh

  # WASM Validation Test
  test-wasm:
    build:
      context: .
      dockerfile: Dockerfile.wasm.test
    container_name: ruv-swarm-test-wasm
    environment:
      - TEST_ENV=docker-wasm
      - RUST_LOG=warn
      - WASM_MEMORY_INITIAL=16777216  # 16MB
    volumes:
      - ./test-results/wasm:/app/test-results
    command: node test/validate-wasm-loading.js

  # Performance Benchmark
  test-performance:
    build:
      context: .
      dockerfile: Dockerfile.perf.test
    container_name: ruv-swarm-test-performance
    environment:
      - TEST_ENV=docker-perf
      - RUST_LOG=warn
    volumes:
      - ./test-results/performance:/app/test-results
    command: node test/docker-performance-suite.js

  # MCP Server Test
  test-mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp.test
    container_name: ruv-swarm-test-mcp
    environment:
      - TEST_ENV=docker-mcp
      - RUST_LOG=warn
      - MCP_TEST_MODE=true
    ports:
      - "3000:3000"
    volumes:
      - ./test-results/mcp:/app/test-results
    command: node test/docker-mcp-validation.js

  # Cross-platform Test
  test-cross-platform:
    build:
      context: .
      dockerfile: Dockerfile.alpine.test
    container_name: ruv-swarm-test-alpine
    environment:
      - TEST_ENV=docker-alpine
      - RUST_LOG=warn
    volumes:
      - ./test-results/alpine:/app/test-results
    command: npm run test:docker:cross-platform

networks:
  default:
    name: ruv-swarm-test-network